server:
  port: 8700
spring:
  application:
    name: edu-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
feign:
  httpclient:
    enabled: true