server:
  port: 7000
spring:
  application:
    name: edu-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: teacher_route
          uri: lb://edu-teacher-management
          order: 1
          predicates:
            - Path=/teacher_serv/**
          filters:
            - StripPrefix=1

        - id: course_route
          uri: lb://edu-course-management
          predicates:
            - Path=/edu-course-management/**
          filters:
            - StripPrefix=1

        - id: oss_route
          uri: lb://edu-aliyun-oss
          predicates:
            - Path=/edu-aliyun-oss/**
          filters:
            - StripPrefix=1

        - id: statistics_route
          uri: lb://edu-statistics-center
          order: 1
          predicates:
            - Path=/edu-statistics-center/**
          filters:
            - StripPrefix=1

        - id: membercenter_route
          uri: lb://edu-member-center
          order: 1
          predicates:
            - Path=/edu-member-center/**
          filters:
            - StripPrefix=1

        - id: video_route
          uri: lb://edu-video
          order: 1
          predicates:
            - Path=/edu-video/**
          filters:
            - StripPrefix=1

        - id: order_route
          uri: lb://edu-order
          order: 1
          predicates:
            - Path=/edu-order/**
          filters:
            - StripPrefix=1

        - id: pay_route
          uri: lb://edu-payment
          order: 1
          predicates:
            - Path=/edu-payment/**
          filters:
            - StripPrefix=1

        - id: article_route
          uri: lb://edu-article-management
          predicates:
            - Path=/edu-article-management/**
          filters:
            - StripPrefix=1

        - id: institution_route
          uri: lb://edu-institution-management
          predicates:
            - Path=/edu-institution-management/**
          filters:
            - StripPrefix=1

  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 0.1