aliyun:
  vod:
    file:
      keyid: LTAI4FeaHtyyBavbWNQFLcpm
      keysecret: HRcgxHt20i7BKA8TQjIXlZ8F0G0dCw
server:
  port: 8900
spring:
  application:
    name: edu-video
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
      base-url: http://127.0.0.1:9411/
      discovery-client-enabled: false
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB